---
title: Tabs
notes: 
status: ready # prototype, wip, ready
default: "tabs" # http://fractal.build/guide/components/variants#the-default-variant
variants:
  - name: tabs
    context:
      modifier: classic-tabs
  - name: tabs no line
    context:
      modifier: classic-tabs-no-line
