# ======================
# CI Stages
# ======================

stages:
  - build
  - deploy

# ======================
# Global variables
# ======================

variables:
  DOCKER_DRIVER: overlay2
  BASE_VERSION: "1.0."
  EXTERNAL_DOCKER_HOST: tcp://localhost:50000
  SERVICE_NAME: componentlibrary

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        export DOCKER_TAG="$BASE_VERSION$CI_PIPELINE_ID";
      else
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG";
      fi;
    - apk --no-cache add python py-pip
    - pip install --upgrade docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker-compose -f docker-compose-prod.yml build
    - docker-compose -f docker-compose-prod.yml push

deploy:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        export DOCKER_TAG="$BASE_VERSION$CI_PIPELINE_ID";
      else
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG";
      fi;
    - apk --no-cache add openssh
    - mkdir ~/.ssh/ && echo $SSH_PRIVATE_KEY > ~/.ssh/id_ed25519
  script:
    - curl icanhazip.com
    - ssh -M -S docker-socket -fnNT -L 50000:localhost:2375 enrise-docker-deploy@185.71.61.61
    - DOCKER_HOST=$EXTERNAL_DOCKER_HOST docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - DOCKER_HOST=$EXTERNAL_DOCKER_HOST docker stack deploy --with-registry-auth --compose-file=docker-compose-prod.yml ${SERVICE_NAME}
    - ssh -S docker-socket -O exit enrise-docker-deploy@185.71.61.61
#  only:
#    - master
