# ======================
# CI Stages
# ======================

stages:
  - build
  - deploy

# ======================
# Global variables
# ======================

variables:
  DOCKER_DRIVER: overlay2
  BASE_VERSION: "1.0."
  SERVICE_NAME: componentlibrary

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        export DOCKER_TAG="$BASE_VERSION$CI_PIPELINE_ID";
      else
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG";
      fi;
    - apk --no-cache add python py-pip
    - pip install --upgrade docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} -f Dockerfile-prod .
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}

deploy:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        export DOCKER_TAG="$BASE_VERSION$CI_PIPELINE_ID";
      else
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG";
      fi;
    - apk --no-cache add openssh
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir /root/.ssh/
    - ssh-keyscan -H 'acc01.nijmegen.cobytes.io' >> ~/.ssh/known_hosts
    - ssh-keyscan -H 'jump01.nijmegen.cobytes.io' >> ~/.ssh/known_hosts
    - rm -f docker-socket-ssh
  script:
    - ssh -o ProxyCommand="ssh -W %h:%p -q enrise@jump01.nijmegen.cobytes.io" -M -S docker-socket-ssh -fnNT -L 50040:127.0.0.1:2375 enrise-docker-deploy@acc01.nijmegen.cobytes.io
    - ssh -S docker-socket-ssh -O check enrise-docker-deploy@acc01.nijmegen.cobytes.io
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker stack deploy --with-registry-auth --compose-file=docker-stack-prod.yml ${SERVICE_NAME}
    - ssh -S docker-socket-ssh -O exit enrise-docker-deploy@acc01.nijmegen.cobytes.io
#  only:
#    - master
