# ======================
# CI Stages
# ======================

stages:
  - test
  - build
  - deploy

# ======================
# Global variables
# ======================

variables:
  DOCKER_DRIVER: overlay2
  SERVICE_NAME: componentlibrary-versioned

# ======================
# Snippets
# ======================

.prepare-deploy: &prepare-deploy
  stage: deploy
  services:
    - docker:dind
  before_script:
    - export DOCKER_TAG="$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID";
    - apk --no-cache add openssh
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add private key
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    # Add host keys
    - mkdir /root/.ssh/
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    # Cleanup old socket
    - rm -f docker-socket-ssh
  artifacts:
    paths:
      - docker-compose-stack.yml
    expire_in: 1 week
    when: always
  only:
    - /^release\/.*$/

# ======================
# Testing
# ======================

jest:
  stage: test
  image: node:8.15.1-alpine
  script:
    - npm ci
    - npm run test

# ======================
# Build stage
# ======================

build release:
  stage: build
  image: tiangolo/docker-with-compose
  services:
  - docker:dind
  before_script:
  - export MAJOR_VERSION_NUMBER=$(echo "${CI_COMMIT_REF_NAME}" | tail -c 2)
  - export CHANGES_FILE_COUNT=$(ls changelogs/unreleased/ | wc -l)
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git config --global user.email "epic@enrise.com" ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git config --global user.name "epic" ; fi
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export DOCKER_TAG="$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID"
  script:
  - docker build . -t "$CI_REGISTRY_IMAGE":$DOCKER_TAG -f Dockerfile-prod
  - docker push "$CI_REGISTRY_IMAGE":$DOCKER_TAG
  - docker run
    -w /app
    -v "$PWD":/app
    -e GITLAB_TOKEN
    -e CI_COMMIT_REF_NAME
    -e CI_REGISTRY_IMAGE
    -e DOCKER_TAG
    -e STABLE_RELEASE
    node:8.15.1-alpine
    npm ci && npm run update-releases
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git fetch origin ${CI_COMMIT_REF_NAME} ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git checkout ${CI_COMMIT_REF_NAME} ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git pull origin ${CI_COMMIT_REF_NAME} ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then npm run update-changelog "${MAJOR_VERSION_NUMBER}.0.0" ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git add --all ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git commit -m "${CI_COMMIT_REF_NAME} changelog update" ; fi
  - if [ ${CHANGES_FILE_COUNT} -gt 0 ] ; then git push https://gitlab-ci-token:${GNIJ_ACCESS_TOKEN}@gitlab.enrise.com/Epic/nijmegen-component-library.git/ ; fi
  only:
    - /^release\/.*$/

build test:
  stage: build
  image: tiangolo/docker-with-compose
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export DOCKER_TAG="$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID";
  script:
    - docker build . -f Dockerfile-prod
  except:
    - /^release\/.*$/

# ======================
# Deploy stage
# ======================

deploy acceptance:
  environment:
    name: acceptance
    url: https://componenten.acc.nijmegen.nl
  <<: *prepare-deploy
  script:
    # Setup SSH tunnel to Docker Engine
    - ssh -o ProxyCommand="ssh -W %h:%p -q enrise@jump01.nijmegen.cobytes.io" -M -S docker-socket-ssh -fnNT -L 50040:127.0.0.1:2375 enrise-docker-deploy@acc01.nijmegen.cobytes.io
    - ssh -S docker-socket-ssh -O check enrise-docker-deploy@acc01.nijmegen.cobytes.io
    # Let Docker authenticate against the GitLab registry
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker login -u gitlab+deploy-token-2 -p $DEPLOY_TOKEN $CI_REGISTRY
    # Generate docker-compose.yml
    - docker run
      -w /app
      -v "$PWD":/app
      -e GITLAB_TOKEN
      -e CI_COMMIT_REF_NAME
      -e CI_REGISTRY_IMAGE
      -e CI_ENVIRONMENT_URL
      -e DOCKER_TAG
      -e STABLE_RELEASE
      node:8.15.1-alpine
      npm run prepare-deployment
    # Deploy the stack
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker stack deploy --with-registry-auth --compose-file=docker-compose-stack.yml ${SERVICE_NAME}
    # Exit SSH tunnel
    - ssh -S docker-socket-ssh -O exit enrise-docker-deploy@acc01.nijmegen.cobytes.io

deploy production:
  environment:
    name: production
    url: https://componenten.nijmegen.nl
  when: manual
  <<: *prepare-deploy
  script:
    # Setup SSH tunnel to Docker Engine
    - ssh -o ProxyCommand="ssh -W %h:%p -q enrise@jump01.nijmegen.cobytes.io" -M -S docker-socket-ssh -fnNT -L 50040:127.0.0.1:2375 enrise-docker-deploy@containerprod01.nijmegen.cobytes.io
    - ssh -S docker-socket-ssh -O check enrise-docker-deploy@containerprod01.nijmegen.cobytes.io
    # Let Docker authenticate against the GitLab registry
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker login -u gitlab+deploy-token-2 -p $DEPLOY_TOKEN $CI_REGISTRY
    # Generate docker-compose.yml
    - docker run
      -w /app
      -v "$PWD":/app
      -e GITLAB_TOKEN
      -e CI_COMMIT_REF_NAME
      -e CI_REGISTRY_IMAGE
      -e CI_ENVIRONMENT_URL
      -e DOCKER_TAG
      -e STABLE_RELEASE
      node:8.15.1-alpine
      npm run prepare-deployment
    # Deploy the stack
    - DOCKER_HOST=tcp://127.0.0.1:50040 docker stack deploy --with-registry-auth --compose-file=docker-compose-stack.yml ${SERVICE_NAME}
    # Exit SSH tunnel
    - ssh -S docker-socket-ssh -O exit enrise-docker-deploy@containerprod01.nijmegen.cobytes.io
