files:
  include:
    - 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/scss/mdb/**/*'

options:
  cache-config: true
  merge-default-rules: false

rules:
  attribute-quotes: 1
  border-zero: 1
  clean-import-paths: 1
  declarations-before-nesting: 2
  final-newline: 1
  function-name-format: 1
  hex-length: 1
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: false
  max-file-line-count: 1
  max-line-length: 
    - 1
    - length: 120
  mixin-name-format: 1
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 1
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 1
  one-declaration-per-line: 2
  property-sort-order: 0
  quotes: 2
  shorthand-values: 1
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-colon: 2
  space-between-parens: 2
  variable-name-format: 1
  zero-unit: 1

syntax:
  include:
    - sass
