version: "3"
services:
  frontend:
    build: .
    command: "npm run start"
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      HTML_VALIDATOR_URL: http://html-validator:8888
    ports:
      - 3000:3000
    networks:
      - nijmegen

  html-validator:
    image: validator/validator:latest
    networks:
      - nijmegen

  regression:
    image: enrise/puppeteer-cucumber:2.2
    volumes:
      - ./test/regression/features:/home/node/app/features
      - ./test/regression/results:/home/node/app/test
      - ./test/regression/node_modules:/home/node/app/node_modules
    user: ${USERID:-1000}:${GROUPID:-1000}
    networks:
      - nijmegen
    environment:
      - ROOT_URL=http://frontend:3000

  static:
    image: nginx:1.17-alpine
    volumes:
      - ./root:/var/www/root:ro
      - ./build:/var/www/dev:ro
      - ./dev/dockerconfig/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - nijmegen
    ports:
      - 3001:3001

networks:
  nijmegen:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.84.0/24
