version: "3"
services:
  frontend:
    build: .
    command: "npm run start"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - HTML_VALIDATOR_URL=http://html-validator:8888
      - PORT
    labels:
      - traefik.enable=true
      - traefik.http.routers.nijmegen.rule=Host(`componenten.nijmegen.dev`)
      - traefik.http.routers.nijmegen.tls=true
      - traefik.http.services.nijmegen.loadbalancer.server.port=80
    networks:
      nijmegen:
        aliases:
          - "componenten.nijmegen.nl"
          - "componenten.nijmegen.dev"

  html-validator:
    image: ghcr.io/validator/validator:21.7.10
    networks:
      - nijmegen

  regression:
    image: enrise/puppeteer-cucumber:3.0
    volumes:
      - ./test/regression/features:/home/node/app/features
      - ./test/regression/results:/home/node/app/test
      - ./test/regression/node_modules:/home/node/app/node_modules
    networks:
      - nijmegen
    environment:
      - ROOT_URL=https://componenten.nijmegen.nl
      - LOCAL=true

  static:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        VERSION: ${VERSION:-dev}
    networks:
      - nijmegen
    ports:
      - 3001:80
    container_name: static
    
networks:
  nijmegen:
    name: nijmegen
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.84.0/24
