FROM node:12.14-alpine as build

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci

COPY ./ /app

ARG VERSION
ENV PUBLIC_URL=/${VERSION}

RUN npm run build

FROM nginx:1.17-alpine as prod

ARG VERSION

RUN echo "Copy files to folder ${VERSION}"
COPY --from=build /app/root /usr/share/nginx/html
COPY --from=build /app/build /usr/share/nginx/html/${VERSION}
