FROM node:10-alpine as builder
ARG NODE_ENV=production

RUN apk add --no-cache git

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json package-lock.json /usr/src/app/
RUN npm ci
COPY . /usr/src/app
RUN npm run create-components-listing
RUN npm run build

FROM nginx:1.13.5-alpine
COPY dev/dockerconfig/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
RUN chown nginx.nginx /usr/share/nginx/html/ -R
