FROM node:12.14-alpine as build

# install python for deasync@0.1.15
RUN apk add g++ make py3-pip

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci

COPY ./ /app

ARG VERSION
ENV PUBLIC_URL=/${VERSION}

RUN npm run build

FROM nginx:1.17-alpine as prod

ARG VERSION

COPY --from=build /app/root /usr/share/nginx/html
COPY --from=build /app/build /usr/share/nginx/html/${VERSION}
RUN echo "Copied files to folder ${VERSION}"
