---
title: Button
notes:
status: ready # prototype, wip, ready
context:
  label: Button label
  label-disabled: Button disabled
  label-link: Button link
default: "info" # http://fractal.build/guide/components/variants#the-default-variant
variants:
  - name: info
    label: "Info"
    context:
      modifier: info
  - name: primary
    context:
      modifier: primary
  - name: secondary
    context:
      modifier: secondary
