context:
  searchAction: "https://www.nijmegen.nl"
  menuComponent: true
  searchComponent: true
  hamburgerIcon: true
  logo: true
  smoothScroll: " smooth-scroll"
  variant: navbar-primary
  light: false
