---
title: Navbar White
status: ready # prototype, wip, ready
default: "default" # http://fractal.build/guide/components/variants#the-default-variant
preview: "@preview-navbar-menu"
context:
  searchComponent: true
  smoothScroll: " smooth-scroll"
variants:
  - name: "default"
  - name: "no-search"
    context:
      searchComponent: false
