---
title: Navbar
status: ready # prototype, wip, ready
default: "default" # http://fractal.build/guide/components/variants#the-default-variant
context:
  menuComponent: true
  searchComponent: true
  hamburgerIcon: true
  smoothScroll: " smooth-scroll"
  searchAction: ""
  variant: navbar-primary
  light: false
variants:
  - name: "default"
  - name: "default-white"
    context:
      variant: navbar-light
      light: true
  - name: "no-search"
    context:
      menuComponent: true
      searchComponent: false
  - name: "no-menu"
    context:
      menuComponent: false
      hamburgerIcon: false
  - name: "no-menu-no-search"
    context:
      menuComponent: false
      searchComponent: false
      hamburgerIcon: false
