#!/bin/bash

BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(expr $BRANCH_NAME : '\(GNIJ-[\0-9]*\)')

# Do not add the issue ID twice if it's already in place.
# This happens e.g. when amending a commit.
if head -n 1 $1 | grep "^$ISSUE_ID"; then
    exit
fi

# If no branch name could be extracted, stop.
if [[ -z "$ISSUE_ID" ]]; then
    exit
fi

# Prepend the issue ID to the commit message.
sed -i.bak -e "1s/^/$ISSUE_ID /" $1

if [ "GNIJ-155" == "$BRANCH_NAME" ]; then
    # Include check to see if file is there
    touch test.txt

    echo "   /==============================="
    echo "   | RELEASE CHANGELOG UPDATED"
    echo "   | Target branch: $BRANCH_NAME"
    echo "   \=============================="
fi
