context:
  searchAction: "searchresults-template.html"
  menuComponent: true
  searchComponent: true
  hamburgerIcon: true
  logo: true
  smoothScroll: " smooth-scroll"
  variant: navbar-primary
  light: false
