---
title: Alerts
notes:
status: prototype # prototype, wip, ready
default: "success" # http://fractal.build/guide/components/variants#the-default-variant
variants:
  - name: success
    context:
      modifier: success
  - name: info
    context:
      modifier: info
  - name: warning
    context:
      modifier: warning
  - name: error
    context:
      modifier: error
