#!/usr/bin/env sh
#
##BRANCH_NAME=$(git symbolic-ref --short HEAD)
#BRANCH_NAME=release/2
#
    echo "   /==============================="
    echo "   | TESTING..."
    echo "   \=============================="
    node dev/release/changelogs/update '1.0.0'
    touch tester2.txt
    date > tester2.txt
#    git add tester.txt
#    git commit -m "$BRANCH_NAME changelog update"
#    git push
#
##if [ "release/" == ${BRANCH_NAME:0:8} ] && [ ! -f test.txt ]; then
#if [ "GNIJ-155" == ${BRANCH_NAME:0:8} ]; then
#    VERSION=${BRANCH_NAME:8:1}
##    touch test.txt
#    date > test.txt
#    git add test.txt
#    git commit -m "$BRANCH_NAME changelog update"
#    git push
#    echo "   /==============================="
#    echo "   | RELEASE CHANGELOG UPDATED"
#    echo "   | Target branch: $BRANCH_NAME"
#    echo "   | Release version: $VERSION"
#    echo "   \=============================="
#fi
