name: 'Deploy to acceptance bucket'

on: [workflow_dispatch]

jobs:
  deploy-to-acceptance:
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: "Setting version varriable"
        run: echo "VERSION=v`helpers/getVersion.sh`" >> "$GITHUB_ENV"

      - name: 'Create release directory'
        run: mkdir release

      - name: 'Run the static build'
        run: docker-compose run static --name=static

      - name: 'Copy html to release directory'
        run: docker cp static:/usr/share/nginx/html release/

      - name: 'Create a deployment in Github'
        uses: chrnorm/deployment-action@releases/v1
        id: acceptance
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          description: 'Deploy to acceptance'
          environment-url: $ACCEPTANCE_URL
          environment: acceptance

      - name: 'Push static files to S3'
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.ACCEPTANCE_AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.ACCEPTANCE_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.ACCEPTANCE_AWS_BUCKET }}
          source_dir: 'release/html'
          destination_dir: '/'

      - name: 'Update deployment status (success)'
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: $ACCEPTANCE_URL/$VERSION
          state: 'success'
          deployment_id: ${{ steps.test.outputs.deployment_id }}

      - name: 'Update deployment status (failure)'
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: $ACCEPTANCE_URL
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
