name: 'Deploy static files to acceptance bucket and create a deployment in Github'
run-name: ${{ github.actor }} deploying to ACCEPTANCE
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy-to-acceptance:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: 
      name: acceptance
      url: ${{ vars.DEPLOY_URL }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: "Setting version varriable"
        run: echo "VERSION=v`helpers/getVersion.sh`" >> "$GITHUB_ENV"

      - name: 'Create release directory'
        run: mkdir release

      - name: 'Run the static build'
        run: docker-compose up -d static

      - name: 'Copy html to release directory'
        run: docker cp static:/usr/share/nginx/html release/

      - name: 'Push static files to S3'
        uses: reggionick/s3-deploy@v3
        with:
          folder: release/html
          bucket: ${{ secrets.AWS_BUCKET }}
          bucket-region: eu-west-1
          delete-removed: true
          no-cache: true
          private: true
