name: 'Sass linting'

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:    
      - main
      - master

jobs:
  sass-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Install node and npm'
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: 'Install packages'
        run: 'npm ci'

      - name: 'Run Sass linter'
        run: 'npm run lint-sass'